plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs9.github.io
baseurl: "/s25"

course: "CS 9"
qtr: "S25"
instructor: "Prof Kate"
quarter: "Spring 2025"
slides_url: https://drive.google.com/drive/folders/1a7vy_RIU21zM9rZ0bHaPg5XrXwEOB7i4?usp=sharing
# ### TODO: check navigation.yml for top-bar links
piazza_url: https://edstem.org/us/courses/77556/discussion
gradescope_url: https://www.gradescope.com/courses/1011615/assignments


github_url: https://github.com/ucsb-cs9/s25

start_week: 1
start_date: 2025-03-30 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true

# ### https://registrar.sa.ucsb.edu/calendars/calendars-deadlines/academic-calendars
# ### https://registrar.sa.ucsb.edu/calendars/quarterly-deadlines

# TODO: make sure that the exam dates are correct on the syllabus as well!
#  https://registrar.sa.ucsb.edu/calendars/final-exams

cal_dates: >                                                                    
  [                                                                            
    {"label":"S25 1st day of instruction", "date":"2025-04-01" },
    {"label":"Academic Integrity Contract Due", "date":"2025-04-09" },
    {"label":"S25 deadline to drop courses w/o W", "date":"2025-04-25" },
    {"label":"S25 CS 9 MIDTERM (3:30pm - 4:45pm)", "date":"2025-05-01" }, 
    {"label":"Holiday: Memorial Day", "date":"2025-05-26" },
    {"label":"S25 instruction ends", "date":"2025-06-06" },
    {"label":"S25 CS 9 FINAL (7:30pm - 9:00pm)", "date":"2025-06-09" }, 
    {"label":"S25 qtr ends", "date":"2025-06-13" }
  ]
#    {"label":"S25 grades due", "date":"2025-06-17" }

kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
